const productTypes = {
    ADD_NEW_PRODUCTS_START: 'ADD_NEW_PRODUCTS_START',
    FETCH_PRODUCTS_START: 'FETCH_PRODUCTS_START',
    SET_PRODUCTS: 'SET_PRODUCTS',
    DELETE_PRODUCT_START: 'DELETE_PRODUCT_START'
};

export default productTypes;